### PR TITLE
Defer adding polyfill script tag until body is defined.

### PR DESCRIPTION
**Pull request by justinfagnani**
Since there's already a 'load' event handler, I just combined the two.

### CODE REVIEW

**Comment by justinfagnani** [comment]
@kevinpschaaf I didn't see #3 which is a simpler fix, but not sure if there's advantages to this approach. Your choice! :)

**Comment by atishpatel** [comment]
I believe this approach makes it so 'webcomponents-lite.min.js' isn't being fetched until after load so it would lead to performance loss while the other one doesn't have that con.

**Comment by JosefJezek** [comment]
Use this script https://github.com/PolymerElements/polymer-starter-kit/blob/psk2/index.html#L34-L65

**Comment by kevinpschaaf** [comment]
Closing, merged #3.

**Pull request closed without merging**
